name: CI

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
            POSTGRES_DB: project_db
            POSTGRES_PASSWORD: eralex
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test database connection
        run: |
          psql -h db -d project_db -U postgres -c 'SELECT 1;'
        env:
            PGPASSWORD: eralex

      - name: Run unit tests
        run: |
          python test_app.py
        env:
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432