name: CI

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
            POSTGRES_DB: postgres_db
            POSTGRES_PASSWORD: eralex
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Start PostgreSQL on Ubuntu
          run: |
            sudo systemctl start postgresql.service
            pg_isready
      - name: Create
        run: |
          sudo -u postgres psql --command="CREATE USER postgres PASSWORD 'eralex'" --command="\du"
      - name: Create timetable database
        run: |
          sudo -u postgres createdb --owner=postgres timetable
          PGPASSWORD=eralex psql --username=postgres --host=localhost --list timetable
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python test_app.py
        env:
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432